default_language_version:
  python: python3

repos:
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-bugbear==21.4.3'
        ]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 5.0.2
    hooks:
      - id: pydocstyle
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
      - id: mypy
        additional_dependencies: [
            'katsdpsigproc==1.2',
            'katsdptelstate==0.11',
            'numpy==1.21.0',
            'types-setuptools==57.0.0'
        ]
