default_language_version:
  python: python3

repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-bugbear==21.4.3'
        ]
        exclude: 'scratch/'
  - repo: https://github.com/pycqa/pydocstyle
    rev: 5.0.2
    hooks:
      - id: pydocstyle
        exclude: 'setup.py|scratch/'  # Because complaining about docstrings here is annoying.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.780'
    hooks:
      - id: mypy
        exclude: 'scratch/'
