default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch # without arguments, master/main will be protected.
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-bugbear==24.12.12',
          'pep8-naming==0.14.1'
        ]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        # Because complaining about docstrings here is annoying. We want to
        # check the benchmarks/ directory because that code is more complex.
        exclude: 'scratch/(?!benchmarks)'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.14.1'
    hooks:
      - id: mypy
        # Passing filenames to mypy can do odd things. See
        # https://github.com/pre-commit/mirrors-mypy/issues/33.
        # mypy.ini determines the set of files that will actually be checked.
        pass_filenames: false
        # The pre-commit hook passes some options, but we set options in mypy.ini.
        args: []
        # The pre-commit hook only has python, not pyi.
        types: []
        types_or: [python, pyi]
        additional_dependencies: [
            'aioconsole==0.8.1',
            'aiokatcp==2.0.2',
            'aiomonitor==0.7.1',
            'asyncssh==2.19.0',
            'dask==2024.12.1',
            'katsdpsigproc==1.8.1',
            'katsdptelstate==0.14',
            'matplotlib==3.10.0',
            'numpy==2.0.2',
            'pandas-stubs==2.2.3.241126',
            'prometheus-client==0.21.1',
            'pyparsing==3.2.1',
            'pytest==8.3.4',
            'redis==5.2.1',  # Indirect dependency of katsdptelstate
            'spead2==4.4.0',
            'types-decorator==5.1.1',
            'types-docutils==0.21.0.20241128',
            'types-setuptools==75.8.0.20250110',  # Indirect dependency
            'types-six==1.17.0.20241205',
            'typing-extensions==4.12.2',
        ]
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.4.1
    hooks:
      - id: pip-compile
        name: pip-compile requirements.txt
        args:
          - --output-file=requirements.txt
          - --extra=gpu
          # Avoid putting extras in the output, so that it can be used for constraints
          - --strip-extras
          - setup.cfg
          - requirements.in
        additional_dependencies:
          - "pip<24.3"  # Workaround for https://github.com/jazzband/pip-tools/issues/2131
        files: '^(requirements\.(in|txt)|setup\.cfg)$'
      - id: pip-compile
        name: pip-compile requirements-dev.txt
        args:
          - --output-file=requirements-dev.txt
          - --extra=test
          - --extra=doc
          - --strip-extras
          - setup.cfg
          - requirements-dev.in
        additional_dependencies:
          - "pip<24.3"  # Workaround for https://github.com/jazzband/pip-tools/issues/2131
        files: '^(requirements(-dev)?\.(in|txt)|setup\.cfg)$'
      - id: pip-compile
        name: pip-compile qualification/requirements.txt
        args:
          - --output-file=qualification/requirements.txt
          - --extra=qualification
          - --strip-extras
          - setup.cfg
          - qualification/requirements.in
        additional_dependencies:
          - "pip<24.3"  # Workaround for https://github.com/jazzband/pip-tools/issues/2131
        files: '(.*requirements(-dev)?\.(in|txt)|^setup\.cfg)$'
      - id: pip-compile
        name: pip-compile scratch/benchmarks/requirements.txt
        args:
          - --output-file=scratch/benchmarks/requirements.txt
          - --strip-extras
          - scratch/benchmarks/requirements.in
        additional_dependencies:
          - "pip<24.3"  # Workaround for https://github.com/jazzband/pip-tools/issues/2131
        files: '(.*requirements(-dev)?\.(in|txt)|^setup\.cfg)$'
