default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch # without arguments, master/main will be protected.
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-bugbear==23.7.10',
          'pep8-naming==0.13.3'
        ]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        # Because complaining about docstrings here is annoying. We want to
        # check the benchmarks/ directory because that code is more complex.
        exclude: 'setup\.py|scratch/(?!benchmarks)'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.4.1'
    hooks:
      - id: mypy
        # Passing filenames to mypy can do odd things. See
        # https://github.com/pre-commit/mirrors-mypy/issues/33.
        # mypy.ini determines the set of files that will actually be checked.
        pass_filenames: false
        # The pre-commit hook passes some options, but we set options in mypy.ini.
        args: []
        # The pre-commit hook only has python, not pyi.
        types: []
        types_or: [python, pyi]
        additional_dependencies: [
            'aiokatcp==1.8.0',
            'asyncssh==2.13.2',
            'dask==2023.7.1',
            'katsdpsigproc==1.8.1',
            'katsdptelstate==0.13',
            'numpy==1.24.4',
            # Note: actual pandas version is 2.0.3, but the stubs for it depend
            # on a newer version of numpy.
            'pandas-stubs==2.0.2.230605',
            'pyparsing==3.0.9',
            'pytest==7.4.0',
            'spead2==4.1.1',
            'types-decorator==5.1.1',
            'types-docutils==0.18.1',
            'types-redis==4.6.0',  # Indirectly needed by katsdptelstate
            'types-setuptools==68.2.0.0',  # Indirectly needed via redis
            'types-six==1.16.0',
        ]
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.1.0
    hooks:
      - id: pip-compile
        name: pip-compile requirements.txt
        args:
          - --output-file=requirements.txt
          - --extra=gpu
          # Avoid putting extras in the output, so that it can be used for constraints
          - --strip-extras
          - setup.cfg
          - requirements.in
        files: '^(requirements\.(in|txt)|setup\.cfg)$'
      - id: pip-compile
        name: pip-compile requirements-dev.txt
        args:
          - --output-file=requirements-dev.txt
          - --extra=test
          - --extra=doc
          - --strip-extras
          - setup.cfg
          - requirements-dev.in
        files: '^(requirements(-dev)?\.(in|txt)|setup\.cfg)$'
      - id: pip-compile
        name: pip-compile qualification/requirements.txt
        args:
          - --output-file=qualification/requirements.txt
          - --extra=qualification
          - --strip-extras
          - setup.cfg
          - qualification/requirements.in
        files: '(.*requirements(-dev)?\.(in|txt)|^setup\.cfg)$'
      - id: pip-compile
        name: pip-compile scratch/benchmarks/requirements.txt
        args:
          - --output-file=scratch/benchmarks/requirements.txt
          - scratch/benchmarks/requirements.in
        files: '(.*requirements(-dev)?\.(in|txt)|^setup\.cfg)$'
