default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch # without arguments, master/main will be protected.
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-bugbear==21.4.3',
          'pep8-naming==0.12.0'
        ]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        exclude: 'setup.py|scratch/'  # Because complaining about docstrings here is annoying.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.942'
    hooks:
      - id: mypy
        # Passing filenames to mypy can do odd things. See
        # https://github.com/pre-commit/mirrors-mypy/issues/33.
        # mypy.ini determines the set of files that will actually be checked.
        pass_filenames: false
        # The pre-commit hook passes some options, but we set options in mypy.ini.
        args: []
        # The pre-commit hook only has python, not pyi.
        types: []
        types_or: [python, pyi]
        additional_dependencies: [
            'aiokatcp==1.3.0',
            'dask==2022.05.0',
            'katsdpsigproc==1.4.2',
            'katsdptelstate==0.11',
            'numpy==1.21.6',
            'pyparsing==3.0.8',
            'spead2==3.9.1',
            'types-decorator==5.1.1',
            'types-docutils==0.17.1',
            'types-redis==4.2.2',
            'types-setuptools==57.0.0',
            'types-six==1.16.0',
        ]
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.6.0
    hooks:
      - id: pip-compile
        name: pip-compile requirements.in
        args: [requirements.in]
        files: ^requirements\.(in|txt)$
      - id: pip-compile
        name: pip-compile requirements-dev.in
        args: [requirements-dev.in]
        files: ^requirements(-dev)?\.(in|txt)$
