repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch # without arguments, master/main will be protected.
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-format
        types_or: [python, pyi]  # Prevent formatting notebooks
      - id: ruff-check
        types_or: [python, pyi]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.18.2'
    hooks:
      - id: mypy
        # Passing filenames to mypy can do odd things. See
        # https://github.com/pre-commit/mirrors-mypy/issues/33.
        # mypy.ini determines the set of files that will actually be checked.
        pass_filenames: false
        # The pre-commit hook passes some options, but we set options in mypy.ini.
        args: []
        # The pre-commit hook only has python, not pyi.
        types: []
        types_or: [python, pyi]
        additional_dependencies: [
            'aioconsole==0.8.1',
            'aiokatcp==2.2.0',
            'aiomonitor==0.7.1',
            'asyncssh==2.21.0',
            'dask==2025.9.1',
            'katsdpsigproc==1.10.0',
            'katsdptelstate==1.0.0',
            'matplotlib==3.10.6',
            'numpy==2.3.3',
            'pandas-stubs==2.3.2.250827',
            'prometheus-client==0.23.1',
            'pyparsing==3.2.5',
            'pytest==8.4.2',
            'redis==6.4.0',  # Indirect dependency of katsdptelstate
            'spead2==4.4.0',
            'types-decorator==5.2.0.20250324',
            'types-docutils==0.21.0.20250809',
            'types-six==1.17.0.20250515',
            'typing-extensions==4.15.0',
        ]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.20
    hooks:
      - id: pip-compile
        name: pip-compile requirements.txt
        args:
          - --output-file=requirements.txt
          - --extra=gpu
          - --python-version=3.12
          - pyproject.toml
          - requirements.in
        files: '^(requirements\.(in|txt)|setup\.cfg)$'
      - id: pip-compile
        name: pip-compile requirements-dev.txt
        args:
          - --output-file=requirements-dev.txt
          - --extra=test
          - --extra=doc
          - --python-version=3.12
          - pyproject.toml
          - requirements-dev.in
        files: '^(requirements(-dev)?\.(in|txt))$'
      - id: pip-compile
        name: pip-compile qualification/requirements.txt
        args:
          - --output-file=qualification/requirements.txt
          - --extra=qualification
          - --python-version=3.12
          - pyproject.toml
          - qualification/requirements.in
        files: '(.*requirements(-dev)?\.(in|txt))$'
      - id: pip-compile
        name: pip-compile scratch/benchmarks/requirements.txt
        args:
          - --output-file=scratch/benchmarks/requirements.txt
          - --python-version=3.12
          - scratch/benchmarks/requirements.in
        files: '(.*requirements(-dev)?\.(in|txt))$'
