default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch # without arguments, master/main will be protected.
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-bugbear==22.6.22',
          'pep8-naming==0.13.0'
        ]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        exclude: 'setup.py|scratch/'  # Because complaining about docstrings here is annoying.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.1.1'
    hooks:
      - id: mypy
        # Passing filenames to mypy can do odd things. See
        # https://github.com/pre-commit/mirrors-mypy/issues/33.
        # mypy.ini determines the set of files that will actually be checked.
        pass_filenames: false
        # The pre-commit hook passes some options, but we set options in mypy.ini.
        args: []
        # The pre-commit hook only has python, not pyi.
        types: []
        types_or: [python, pyi]
        additional_dependencies: [
            'aiokatcp==1.6.0',
            'dask==2022.10.0',
            'katsdpsigproc==1.6.1',
            'katsdptelstate==0.13',
            'numpy==1.23.4',
            'pyparsing==3.0.9',
            'pytest==7.1.3',
            'spead2==3.11.1',
            'types-decorator==5.1.1',
            'types-docutils==0.17.1',
            'types-redis==4.5.3',
            'types-setuptools==57.0.0',
            'types-six==1.16.0',
        ]
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.12.1
    hooks:
      - id: pip-compile
        name: pip-compile requirements.txt
        args:
          - --output-file=requirements.txt
          - --extra=gpu
          - --extra=vkgdr
          # Avoid putting extras in the output, so that it can be used for constraints
          - --strip-extras
          - setup.cfg
          - requirements.in
        files: '^(requirements\.(in|txt)|setup\.cfg)$'
      - id: pip-compile
        name: pip-compile requirements-dev.txt
        args:
          - --output-file=requirements-dev.txt
          - --extra=test
          - --extra=doc
          - --strip-extras
          - setup.cfg
          - requirements-dev.in
        files: '^(requirements(-dev)?\.(in|txt)|setup\.cfg)$'
      - id: pip-compile
        name: pip-compile qualification/requirements.txt
        args:
          - --output-file=qualification/requirements.txt
          - --extra=qualification
          - --strip-extras
          - setup.cfg
          - qualification/requirements.in
        files: '(.*requirements(-dev)?\.(in|txt)|^setup\.cfg)$'
